config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :courses
  root to: 'courses#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_header.html.erb
  <div class="py-8 px-12 w-full">
    <div class="flex w-full justify-between items-center mb-6 md:mb-12">
      <div class="rounded relative w-full w-8/12 md:w-1/3">
        <svg xmlns="http://www.w3.org/2000/svg"
             class="text-gray-500 absolute ml-4 inset-0 m-auto icon icon-tabler icon-tabler-search" width="20"
             height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round"
             stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z"></path>
          <circle cx="10" cy="10" r="7"></circle>
          <line x1="21" y1="21" x2="15" y2="15"></line>
        </svg>
        <input
          class="border border-gray-100 focus:outline-none focus:border-brand rounded-full w-full text-sm bg-gray-100 text-gray-500 pl-12 sm:pl-10 md:pl-12 py-3 pr-4"
          type="text" placeholder="Search"/>
      </div>
      <div class="flex items-center ml-6 md:ml-0">
        <div class="mr-2 md:mr-6">
          <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 28 28" fill="none">
            <path
              d="M11.6667 5.83333C11.6667 4.54467 12.7113 3.5 14 3.5C15.2887 3.5 16.3333 4.54467 16.3333 5.83333C19.0635 7.12431 20.8584 9.81662 21 12.8333V16.3333C21.178 17.8043 22.044 19.1032 23.3333 19.8333H4.66666C5.95596 19.1032 6.82195 17.8043 7 16.3333V12.8333C7.14159 9.81662 8.93647 7.12431 11.6667 5.83333"
              stroke="#718096" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M10.5 19.8333V21C10.5 22.933 12.067 24.5 14 24.5C15.933 24.5 17.5 22.933 17.5 21V19.8333"
                  stroke="#718096" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </div>
        <img class="" src="https://cdn.tuk.dev/assets/components/todos/profile.png" alt="profile" srcset=""/>
      </div>
    </div>

app/views/courses/_sidebar.html.erb
<div id="sidebar"
     class="overflow-y-scroll lg:overflow-y-auto fixed lg:sticky h-screen z-40 top-0 bg-gray-900 pt-10 w-64 lg:w-72">
  <div class="px-8">
    <div class="flex items-center justify-between">
      <div class="w-32">
        <!--        <img class="w-full" src="https://cdn.tuk.dev/assets/components/todos/logo.png" alt="quicklist logo"/>-->
        <img src="assets/shank-shack.png" alt="Shank Shank logo" class="w-full">
      </div>
      <div onclick="openSidebar(true)" class="text-gray-700 ml-8 cursor-pointer">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-left" width="32"
             height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
             stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z"/>
          <polyline points="15 6 9 12 15 18"/>
        </svg>
      </div>
    </div>
    <ul class="my-10 flex flex-wrap">
      <li class="w-1/2 flex justify-start mb-6">
        <%= link_to courses_path, class: 'bg-transparent rounded-md text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4' do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-map-pin" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#9e9e9e" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <circle cx="12" cy="11" r="3"/>
            <path d="M17.657 16.657l-4.243 4.243a2 2 0 0 1 -2.827 0l-4.244 -4.243a8 8 0 1 1 11.314 0z"/>
          </svg>
          <p class="mt-1 uppercase font-semibold text-xs">Courses</p>
        <% end %>
      </li>
      <li class="w-1/2 flex justify-end mb-6">
        <a href="./inbox.html"
           class="bg-transparent rounded-md text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-inbox" width="20" height="20"
               viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round"
               stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z"/>
            <rect x="4" y="4" width="16" height="16" rx="2"/>
            <path d="M4 13h3l3 3h4l3 -3h3"/>
          </svg>
          <p class="mt-1 uppercase font-semibold text-xs">inbox</p>
        </a>
      </li>
      <li class="w-1/2 flex justify-start mb-6">
        <%= link_to '#', class: "rounded-md bg-transparent text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-tournament" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#9e9e9e" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M5 4h4a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1h-4" />
  <path d="M5 14h4a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1h-4" />
  <path d="M10 7h4a1 1 0 0 1 1 1v8a1 1 0 0 1 -1 1h-4" />
  <line x1="15" y1="12" x2="20" y2="12" />
</svg>
          <p class="mt-1 uppercase font-semibold text-xs">Standings</p>
        <% end %>
      </li>
      <li class="w-1/2 flex justify-end mb-6">
        <a href="./calendar_month_view.html"
           class="rounded-md bg-transparent text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4">
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#9e9e9e" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <rect x="4" y="5" width="16" height="16" rx="2" />
  <line x1="16" y1="3" x2="16" y2="7" />
  <line x1="8" y1="3" x2="8" y2="7" />
  <line x1="4" y1="11" x2="20" y2="11" />
  <line x1="11" y1="15" x2="12" y2="15" />
  <line x1="12" y1="15" x2="12" y2="18" />
</svg>
          <p class="mt-1 uppercase font-semibold text-xs">calendar</p>
        </a>
      </li>
      <li class="w-1/2 flex justify-start">
        <%= link_to '#', class: 'rounded-md bg-transparent text-gray-600 flex flex-col justify-center items-center w-20 h-20 p-4' do %>


        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-golf" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#9e9e9e" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <path d="M12 18v-15l7 4l-7 4"/>
            <path d="M9 17.67c-.62 .36 -1 .82 -1 1.33c0 1.1 1.8 2 4 2s4 -.9 4 -2c0 -.5 -.38 -.97 -1 -1.33"/>
          </svg>
          <p class="mt-1 uppercase font-semibold text-xs">Rounds</p>
        <% end %>
      </li>
      <li class="w-1/2 flex justify-end">
        <a href="./projects.html"
           class="rounded-md bg-gray-700 text-gray-300 flex flex-col justify-center items-center w-20 h-20 p-4">
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-coin" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#9e9e9e" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <circle cx="12" cy="12" r="9" />
  <path d="M14.8 9a2 2 0 0 0 -1.8 -1h-2a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4h-2a2 2 0 0 1 -1.8 -1" />
  <path d="M12 6v2m0 8v2" />
</svg>
          <p class="mt-1 uppercase font-semibold text-xs">Wagers</p>
        </a>
      </li>
    </ul>
    <div class="flex items-center justify-between text-gray-light hover:text-gray-600">
      <h4 class="uppercase font-semibold bg-gray-900 cursor-pointer">Upload a Score</h4>
      <svg xmlns="http://www.w3.org/2000/svg" class="cursor-pointer icon icon-tabler icon-tabler-plus" width="20"
           height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round"
           stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z"/>
        <line x1="12" y1="5" x2="12" y2="19"/>
        <line x1="5" y1="12" x2="19" y2="12"/>
      </svg>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schnorrcard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;500;700;900&display=swap" rel="stylesheet"/>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="flex flex-no-wrap">
    <div onclick="openSidebar(false)"
         class="flex items-center justify-center rounded-r-md bg-gray-800 text-gray-300 ml-0 cursor-pointer absolute inset-0 mt-10 m-auto w-8 h-8">
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-right" width="28" height="28"
           viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round"
           stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z"/>
        <polyline points="9 6 15 12 9 18"/>
      </svg>
    </div>
    <%= render partial: 'sidebar' %>
    <%= render partial: 'header' %>
    <%= yield %>
  </div>
  </body>
</html>

<script type="text/javascript" charset="utf-8">
  // Inbox script starts
  let elements = document.querySelectorAll("[data-menu]");
  for (let i = 0; i < elements.length; i++) {
    let main = elements[i];
    main.addEventListener("click", function () {
      let element = main.parentElement.parentElement;
      let andicators = main.querySelectorAll("svg");
      let child = element.querySelector("ul");
      child.classList.toggle("hidden");
      if (child.classList[1] !== "hidden") {
        andicators[1].style.display = "block";
        andicators[0].style.display = "none";
      } else {
        andicators[1].style.display = "none";
        andicators[0].style.display = "block";
      }
    });
  }
  //Inbox script ends

  // Notebook script starts
  function dropdownFunction(element) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    let list = element.parentElement.parentElement.getElementsByClassName("dropdown-content")[0];
    for (i = 0; i < dropdowns.length; i++) {
      dropdowns[i].classList.add("hidden");
    }
    list.classList.toggle("hidden");
  }

  window.onclick = function (event) {
    if (!event.target.matches(".dropbtn")) {
      var dropdowns = document.getElementsByClassName("dropdown-content");
      var i;
      for (i = 0; i < dropdowns.length; i++) {
        var openDropdown = dropdowns[i];
        openDropdown.classList.add("hidden");
      }
    }
  };
  let flag = true;

  function checkAll() {
    if (flag) {
      document.querySelectorAll('input[type="checkbox"]').forEach((el) => {
        el.nextElementSibling.classList.remove("hidden");
      });
      flag = false;
    } else {
      document.querySelectorAll('input[type="checkbox"]').forEach((el) => {
        el.nextElementSibling.classList.add("hidden");
      });
      flag = true;
    }
  }

  // Reroute
  goToNotes = () => {
    window.location.href = "./notes.html";
  };
  goToTodos = () => {
    window.location.href = "app/views/layouts/todos.html.erb";
  };
  // Notebook script ends
  openSidebar = (flag) => {
    let sidebar = document.getElementById("sidebar");
    flag ? sidebar.classList.add("hidden") : sidebar.classList.remove("hidden");
  };
  //popup

  const Popup = (flag) => {
    if (flag) {
      document.getElementById("popup").classList.add("right-100");
      document.getElementById("popup").classList.remove("hidden");
    } else {
      document.getElementById("popup").classList.add("hidden");
    }
  };
  const Popup_review = (flag) => {
    if (flag) {
      document.getElementById("popup").classList.add("hidden");
      document.getElementById("popup_review").classList.remove("hidden");
    } else {
      document.getElementById("popup_review").classList.add("hidden");
    }
  };

  const selection = (flag) => {
    if (flag) {
      document.getElementById("check").classList.add("md:flex");
      document.getElementById("check").classList.remove("hidden");
    } else {
      document.getElementById("check").classList.remove("md:flex");
      document.getElementById("check").classList.add("hidden");
    }
  };

</script>